---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(tm)
library(caret)
library(wordcloud)
library(e1071)
```


# Data Understanding

```{r}
url = "https://raw.githubusercontent.com/businessdatasolutions/courses/main/data%20mining/gitbook/datasets/smsspam.csv"
rawDF = read.csv(url)
head(rawDF)
```


# Data Preparation

We will convert the label variable into a factor data type.
```{r}
rawDF$type <- rawDF$type %>% factor %>% relevel("spam")
class(rawDF$type)
```


```{r}
spam <- rawDF %>% filter(type == "spam")
ham <- rawDF %>% filter(type == "ham")

wordcloud(spam$text, max.words = 20, scale = c(4, 0.8), colors= c("indianred1","indianred2","indianred3","indianred"))
wordcloud(ham$text, max.words = 20, scale = c(4, 0.8), colors= c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))
```
Convert text to corpus

```{r}
rawCorpus <- Corpus(VectorSource(rawDF$text))
inspect(rawCorpus[1:3])
```
We make lowercase and remove numbers

```{r}
cleanCorpus <- rawCorpus %>% tm_map(tolower) %>% tm_map(removeNumbers)
```
We remove stopword, punctuation and whitespaces

```{r}
cleanCorpus <- cleanCorpus %>% tm_map(removeWords, stopwords()) %>% tm_map(removePunctuation) %>% tm_map(stripWhitespace)

```

Build DTM

```{r}
cleanDTM <- cleanCorpus %>% DocumentTermMatrix
inspect(cleanDTM)
```

Split dataset into training and testing

```{r}
# Create split indices
set.seed(1234)
trainIndex <- createDataPartition(rawDF$type, p = .75, 
                                  list = FALSE, 
                                  times = 1)
head(trainIndex)
```
```{r}
trainDF <- rawDF[trainIndex, ]

testDF <- rawDF[-trainIndex, ]

```

```{r}
testDF <- rawDF[-trainIndex, ]

# Apply split indices to Corpus
trainCorpus <- cleanCorpus[trainIndex]
testCorpus <- cleanCorpus[-trainIndex]

# Apply split indices to DTM
trainDTM <- cleanDTM[trainIndex, ]
testDTM <- cleanDTM[-trainIndex, ]
```

Now we will remove infrequent words

```{r}
freqWords <- trainDTM %>% findFreqTerms(5)
trainDTM <-  DocumentTermMatrix(trainCorpus, list(dictionary = freqWords))
testDTM <-  DocumentTermMatrix(testCorpus, list(dictionary = freqWords))
```

